# Generated by Django 2.0.5 on 2018-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=100, verbose_name='Nome do estabelecimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço do estabelecimento')),
            ],
            options={
                'ordering': ('nome_estabelecimento',),
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
    ]
